spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=pizza_store;encrypt=true;trustServerCertificate=true
spring.datasource.username=root
spring.datasource.password=YOUR_DATABASE_PASSWORD_HERE

jwt.secretKey=YOUR_JWT_SECRET_KEY_HERE
jwt.expiration=3600000
jwt.refresh-expiration=604800000

cloudinary.cloud-name=YOUR_CLOUDINARY_CLOUD_NAME_HERE
cloudinary.api-key=YOUR_CLOUDINARY_API_KEY_HERE
cloudinary.api-secret=YOUR_CLOUDINARY_API_SECRET_HERE

app.cors.allowed-origins=http://localhost:4200